#!/usr/bin/env python3
"""Build one exact-subject NormShift external-audit package."""

from __future__ import annotations

import argparse
import importlib.metadata
import os
import shutil
import subprocess
import sys
from pathlib import Path

sys.dont_write_bytecode = True

ROOT = Path(__file__).resolve().parents[1]
BOOTSTRAP_MARKER = "NORMSHIFT_PACKAGE_BUILDER_BOOTSTRAPPED"
BOOTSTRAP_REQUIREMENTS = (
    "jsonschema==4.26.0",
    "packaging==26.3",
    "cyclonedx-python-lib[validation]==11.11.0",
)


def _bootstrap() -> int | None:
    if os.environ.get(BOOTSTRAP_MARKER) == "1":
        if sys.version_info[:2] != (3, 12):
            print("error: package builder requires Python 3.12", file=sys.stderr)
            return 1
        for requirement in BOOTSTRAP_REQUIREMENTS:
            distribution, expected = requirement.split("==", maxsplit=1)
            distribution = distribution.split("[", maxsplit=1)[0]
            if importlib.metadata.version(distribution) != expected:
                print(f"error: bootstrap dependency mismatch: {requirement}", file=sys.stderr)
                return 1
        return None
    uv = shutil.which("uv")
    if uv is None:
        print("error: uv is required to bootstrap the exact package builder", file=sys.stderr)
        return 1
    environment = os.environ.copy()
    environment[BOOTSTRAP_MARKER] = "1"
    command = [uv, "run", "--no-project", "--python", "3.12"]
    for requirement in BOOTSTRAP_REQUIREMENTS:
        command.extend(("--with", requirement))
    command.extend(("python", "-B", str(Path(__file__).resolve()), *sys.argv[1:]))
    return subprocess.run(command, env=environment, check=False).returncode


def main(argv: list[str] | None = None) -> int:
    sys.path.insert(0, str(ROOT / "src"))
    from normshift.audit.package_build import (
        BuildConfig,
        PackageBuildError,
        build_authoritative_package,
    )

    parser = argparse.ArgumentParser(
        description=(
            "Build a fail-closed M0 audit candidate from one clean, exact Git commit. "
            "The output root must be outside the checkout."
        )
    )
    parser.add_argument("--repo", type=Path, default=ROOT, help="Exact Git checkout root")
    parser.add_argument("--output-root", type=Path, required=True)
    parser.add_argument(
        "--commit",
        required=True,
        help="Full 40-character commit SHA that HEAD must equal",
    )
    parser.add_argument("--repository-url", help="Public https repository URL")
    parser.add_argument("--default-branch", default="master")
    parser.add_argument("--run-id", help="Optional unique safe run ID; generated by default")
    args = parser.parse_args(argv)
    try:
        result = build_authoritative_package(
            BuildConfig(
                repo=args.repo,
                output_root=args.output_root,
                expected_commit=args.commit,
                repository_url=args.repository_url,
                default_branch=args.default_branch,
                run_id=args.run_id,
            )
        )
    except PackageBuildError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1
    print(result)
    return 0


if __name__ == "__main__":
    bootstrap_result = _bootstrap()
    raise SystemExit(main() if bootstrap_result is None else bootstrap_result)
